### ISSUE TITLE
problem integrating this code into my project

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [bauerca/drag-sort-listview#1]
hi bauerca

i tried to compile the demos in Eclipse, which didn't work, so i decided to try integrating the dslv straight into my codebase.
that doesn't work either, because of this

<ImageView android:id="@id/drag"

Description Resource    Path    Location    Type
error: Error: No resource found that matches the given name (at 'id' with value '@id/drag').    plitem.xml  

i tried replacing it with @+id/drag, and now it compiles and runs. but still no drag-n-drop.

can you help me out?

here's how i integrated your stuff into my project
1. copied all relevant files to my source tree
2. changed the ListView to DragSortListView
3. added the drag image with @+id/drag to my list item
4. added onDrop and onRemove handlers, just like in your demos (empty implementations for now)

everything else remained as it was before the change.

the biggest differences compared to the demos are following
- i'm not using ListActivity, so the code looks like this:

setContentView(R.layout.main);
FileListAdapter adapter = new FileListAdapter(this, R.layout.list_item);
DragSortListView lst = (DragSortListView) findViewById(R.id.listview);
lst.setAdapter(adapter);
lst.setDropListener(onDrop);
lst.setRemoveListener(onRemove);
- i'm not using ArrayAdapter
  instead, i'm using my own FileListAdapter, which extends BaseAdapter

**Comment by Oleksiy-Yakovenko** [comment]
nvm, i found the problem -- i was already overloading the listview's onTouch, and forgot to remove it.

**Comment by bauerca** [comment]
Hi oleksiyy. Thanks for trying this out. I'm wondering if you could try the demos again in Eclipse. I've modified the path to DSLV.java, which seemed to be the source of confusion. It now compiles and runs for me.

Here's my step-by-step for anyone who needs it:

On the cmd line:
1. git clone https://github.com/bauerca/drag-sort-listview.git
2. cd drag-sort-listview/
3. android update project --path ./ --subprojects

Then in Eclipse (for the demo project):
4. File -> New -> Project... -> Android Project
5. name your project (e.g. "demodslv")
6. Select "Create project from existing source"
7. Location: /path/to/drag-sort-listview/demo
8. Next
9. Choose your API level
10. Package name: com.mobeta.android.demodslv (important)
11. Finish

Then (for the library project):
12. File -> New -> Project... -> Android Project
13. name your project (e.g. "dslv")
14. Select "Create project from existing source"
15. Location: /path/to/drag-sort-listview
16. Next
17. Choose your API level
18. Package name: com.mobeta.android.dslv (important)
19. Finish

(oleksiyy, glad to hear copy and paste worked; just got your msg)

**Comment by Oleksiy-Yakovenko** [comment]
thanks for the answer. i will try the demos as soon as i have some free time :)
i still didn't get the stuff working, will continue soon.

can you explain the <ImageView android:id="@id/drag"

i assume this xml code works for you, but it only works for me if i change it to @+id/drag

p.s. i'm using api level 4, if that matters.

**Comment by bauerca** [comment]
The library project (at /path/to/drag-sort-listview) defines an id resource in res/values/ids.xml:

```
<resources>
  <item type="id" name="drag" />
</resources>
```

This id is used in DSLV.java to find the View within a list item layout that initiates the drag. When you do @+id/drag, you are creating a duplicate id in your package scope. If used as a library project, DSLV.java only sees its own R.java, and thus its own drag id (I'm pretty sure). I'm not sure what's happening when you simply move DSLV.java to your project. Do you copy res/values/ids.xml as well? If so, try neglecting that and keeping your @+id/drag statement.

This is a similar approach to the ListActivity, where you have to identify your ListView within the layout by @android:id/list
http://developer.android.com/reference/android/app/ListActivity.html

**Comment by Oleksiy-Yakovenko** [comment]
thanks for the explanation. i've never used ids.xml, and i didn't copy it into my source tree. in my case, i think using @+id/drag is the working solution, because i simply "copy-paste". i'll let you know if it works when i try the demos and fix my code :)

**Comment by Oleksiy-Yakovenko** [comment]
i tried hard, but i still can't get your code to work.. my listview item layout is quite different from what your code expects, and i can't get it to comply -- items display incorrectly, and don't start moving when i drag..

for now i decided to use the android music TouchInterceptor, which almost works  -- i can get list view items to display correctly, and drag/drop works, except doExpansion and scrolling are broken. i think i can figure out these remaining things, and get it working.

sorry for wasting your time, and thanks for your help.

**Comment by Oleksiy-Yakovenko** [comment]
p.s. i shocked how hard it is to do simple things like this one on android

**Comment by bauerca** [comment]
Can you send me your list item layout xml file? I am curious what the issue is here, for future users. Thanks!

**Comment by bauerca** [comment]
Also, I am assuming you couldn't get the demos working?

**Comment by Oleksiy-Yakovenko** [comment]
this is the unmodified layout, it works perfectly with the TouchInterceptor, but when i use it with dslv -- it displays incorrectly.
i didn't  try the demos yet.

moved the layout to pastebin, it doesn't display correctly here.
http://pastebin.com/S49iCZy5

**Comment by bauerca** [comment]
I see an immediate issue. Your topmost LinearLayout uses fill_parent as its layout height. DSLV needs your item to have a definite height (it can be wrap_content). DSLV does not use a normal_height flag like the touch interceptor. This allows DSLV to support arbitrary item heights.

Let me know if this fixes anything. Thanks!

**Comment by Oleksiy-Yakovenko** [comment]
hey Carl.

i was experimenting with the TouchInterceptor, and figured out why my
stuff was failing.

1st thing was the one that you found -- the listview item size must be fixed.
i changed this, and it kindof worked, setting LayoutParams.height
changes the item size. but instead of making a hole between items --
it just stretches the list item background, and keeps the contents
centered vertically.

2nd thing is scrolling. it didn't work correctly, because i was using
scrollBy instead of smoothScrollBy, which is completely wrong.
scrollBy is the View method, and ListView doesn't handle it correctly.
so, as i found out, i can't implement drag'n'drop with API level 4,
because there's no other way to scroll without the smoothScrollBy,
which is sad, becayse i have 10 paying customers on android 2.1, and
don't want to break my application on their phones - because
smoothScrollBy was introduced in API level8.

anyway.. for now i switched to API level8 to get it working, and later
i'll try to figure out how to do fallback implementation for android
2.1.

i still have another problem, that every time when setLayoutParams is
called to resize an item -- there's a severe slowdown. don't know why
yet, but maybe it will go away after i fix the other issue.

for now i'm working with the TouchInterceptor, and since i'm very
close to getting it working -- i'll do this.
then when it works -- i'll try to convert the code to DSLV.

On Thu, Jun 28, 2012 at 8:38 PM, Carl Bauer
reply@reply.github.com
wrote:

**Comment by Oleksiy-Yakovenko** [comment]
yes!

i found the "hole" problem, and fixing it also fixed the slowdowns.

the problem was that my layout was like this

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="64dip"
        android:gravity="center_vertical"
        android:ignoreGravity="@+id/icon"
        android:background="@color/list_item_bg"
        >
... item textviews/images here ....
</RelativeLayout>

but in android music app, this layout is also wrapped in another
linearlayout like this:

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="66dip"
    android:gravity="bottom"
    android:orientation="vertical"
    android:baselineAligned="false">

... the above RelativeLayout here ...
</LinearLayout>

that fixed all problems, and now everything works perfectly. now i
need to cleanup the code a bit, make a backup, and then try your code
again.

**Comment by bauerca** [comment]
Fantastic! Let me know how it goes. I'd really like to get dslv working in your app! 

You can support scrolling in older APIs by using setSelectionFromTop() in place of smoothScrollBy()

**Comment by Oleksiy-Yakovenko** [comment]
hi Carl. i was looking through my list of "mails to followup", and
noticed that i didn't respond to you..

in the end i decided to go with the original TouchInterceptor class,
and it worked out fine for my needs in the end (took several days to
figure out all the quirks though). so sorry for taking your time.
cheers!

On Thu, Jun 28, 2012 at 9:53 PM, Carl Bauer
reply@reply.github.com
wrote:

**Comment by bauerca** [comment]
That's okay. No one else has reported a similar issue; wonder what went wrong. Good luck!

**Comment by Oleksiy-Yakovenko** [comment]
nothing really went wrong.. at first i got stuck at something, and then i
tried with the TouchInterceptor, and then i spent way to much time on it to
go back.

**Comment by bauerca** [comment]
gotcha! thanks.

**Comment by thastings3** [comment]
I am having the exact same issue when trying to use drag-sort-listview as a library project in intellij
