### ISSUE TITLE
How to avoid removing last item from the list

### ISSUE THREAD

**Issue by jihonrado** [bauerca/drag-sort-listview#101]
Hi,

Is there any way to avoid removing last item from the list?

Here is my workaround:

```
    dragSortListView.setRemoveListener(new DragSortListView.RemoveListener() {
        @Override
        public void remove(int which) {
            if (visibleItemsAdapter.getCount() > 1) {
                visibleItemsAdapter.remove(visibleItemsAdapter.getItem(which));
            } else {
                Toast.makeText(activity,
                        getString(R.string.toast_at_least_one_visible_category),
                        Toast.LENGTH_SHORT).show();
            }
            visibleItemsAdapter.notifyDataSetChanged();
        }
    });
```

But this makes a weird effect removing the item and then showing it again with the "notifyDataSetChanged".

Regards

**Comment by Odaym** [comment]
Put that item in the listview's footer

**Comment by AOrobator** [comment]
Or just don't have a drag handle for the last item in the list.

**Comment by asking1233** [comment]
visibleItemsAdapter  may initialize The original  data again.check it.

**Comment by BaronZ** [comment]
hi buddy, just override getFooterViewsCount();
return super.getFooterViewsCount() + 1;
i think this works for u perfectly

**Comment by BaronZ** [comment]
override getFooterViewCount()

**Comment by Odaym** [comment]
Close this already!
