### ISSUE TITLE
Unable to get the list to trigger drag/drop/remove listeners

### ISSUE THREAD

**Issue by bhaskarmurthy** [bauerca/drag-sort-listview#11]
I've added code from the example to my project, the only difference being that my listview is in a fragment, using ActionBarSherlock library.

I don't get any errors etc, but the drag/drop/remove listeners never get triggered.

Is there a known issue w/ compatibility between the two libraries? Any help would be much appreciated. Thanks!

My code looks like below:

public class MyListFragment extends SherlockFragment {
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState) {

```
    View view = inflater.inflate(R.layout.activity_todos, container, false);
        DragSortListView listView = (DragSortListView) view.findViewById(R.id.list);
    // add drag-drop events
    listView.setDragListener(new DragListener() {

        @Override
        public void drag(int from, int to) {
            String item = adapter.getItem(from);

            adapter.remove(item);
            adapter.insert(item, to);

        }
    });

    listView.setDropListener(new DropListener() {
        @Override
        public void drop(int from, int to) {
            String item = adapter.getItem(from);

            adapter.remove(item);
            adapter.insert(item, to);
        }
    });

    listView.setRemoveListener(new RemoveListener() {

        @Override
        public void remove(int which) {
            adapter.remove(adapter.getItem(which));
        }
    });

    return view;
```

}

**Comment by bhaskarmurthy** [comment]
Hey, sorry for the post. Figured out the issue. I didn't have an element w/ @id/drag in my layout. All good now. Thanks!

**Comment by bauerca** [comment]
Glad to hear it!
