### ISSUE TITLE
The width of item layout not fit with of the screen

### ISSUE THREAD

**Issue by MrTranduchuy** [bauerca/drag-sort-listview#117]
Hello,

I don't know I get this problem, I really try to find out information related to my project.
But it seems like related to your library.
1. I make the the simple item layout, like this :
   ![simple_list_item](https://f.cloud.github.com/assets/4351758/1865853/c13f6246-781c-11e3-8208-caa0027be270.PNG)
2. I can load data to show to the Default List View (variable : ListView listView), like this : (It shows exactly)
   ![default_listview](https://f.cloud.github.com/assets/4351758/1865850/a57f2528-781c-11e3-9702-9ed496c53146.png)
3. But when I change from Default List View to your Drag Sort List View (variable : DragSortListView dragSortListView), like this : (It shows wrong construction)
   ![dragsort_listview](https://f.cloud.github.com/assets/4351758/1865861/1dbf116a-781d-11e3-9fb9-0e1663eb9406.png)

It looks like your library use margin?
Can u tell me how to fix this basic problem?

p/s : I have not already used margin, padding yet.

**Comment by johnuopini** [comment]
I'm fighting with this issue since 2 days as well

**Comment by MrTranduchuy** [comment]
I dont know why the sample code not automatically scale as above.

The different of my project and the sample code is : 
I used layout_weight and weightSum in LinearLayout to assign portion of views.

**Comment by johnuopini** [comment]
Please check out this comment, this worked for me:
https://github.com/bauerca/drag-sort-listview/issues/73#issuecomment-13994384

**Comment by MrTranduchuy** [comment]
Oh, it works with me too, thanks.
