### ISSUE TITLE
onitemclick and onitemlongclick events are not being bubbled through

### ISSUE THREAD

**Issue by bhaskarmurthy** [bauerca/drag-sort-listview#13]
I'm trying to get onitemclick and onitemlongclick to work, when the listitem itself is the draggable view (there is no separate drag handle). for some reason the events don't seem to bubble through.

I've posted about this on stackoverflow (http://stackoverflow.com/questions/11958125/setonitemlongclicklistener-and-setonitemclicklistener-are-not-triggered-when-usi), but am raising the question here in case you prefer this list.

Thanks!
- Bhaskar

**Comment by bauerca** [comment]
Hi Bhaskar,

I will look into enabling this functionality soon, as this has been requested before. At the moment, DSLV overrides onInterceptTouchEvent and if an ACTION_DOWN event hits the View with `@id/drag`, the drag is initiated. This process can be made smarter. For instance, a click could (and should) have a higher priority than drag initiation. I'll get back to you on this, and thanks for the accolades on StackOverflow!

Carl

**Comment by bauerca** [comment]
Still looking at this. Wrapping my head around the detailed interactions of onInterceptTouchEvent and onTouchEvent.

**Comment by orac** [comment]
Can I help out with this? It seems to me that the following approach might work:
onInterceptTouchEvent responds to ACTION_DOWN when the touch point is on the 'drag' view by setting up mGestureDetector, and returns false to let the item handle the view. When mGestureDetector exists, onInterceptTouchEvent always passes on the event. The OnGestureListener on the detector responds to onFling as it does now; onScroll by starting a drag; onSingleTap by doing onItemClick; and onLongPress by doing onItemLongClick. Crucially, all the OnGestureListener callbacks cause onInterceptTouchEvent to return true to cancel the item's touch event. This way, onTouchEvent only needs to pass on its event to mGestureDetector, and all the heavy lifting is in the callbacks from that.

I think that would also be a good starting point for doing the long-press-to-drag feature.

**Comment by bauerca** [comment]
Done! Check out what's offered by the DragSortController class and the new API. Thanks @orac for all the initial help on this!
