### ISSUE TITLE
Maven central

### ISSUE THREAD

**Issue by mathieudebrito** [bauerca/drag-sort-listview#137]
Hi there, is there any plan to put this lib on maven central ? or anywhere on the cloud so that we can use it using gradle ?

Most of companies does not allow standalone projects like this.

Thx

PS : only official repository, no forks

**Comment by jitpack-io** [comment]
@mathieudebrito You can also get it on JitPack https://jitpack.io/#bauerca/drag-sort-listview/0.6.1

**Comment by mathieudebrito** [comment]
Ok perfect, thx !
