### ISSUE TITLE
List with layout_margin

### ISSUE THREAD

**Issue by tracyboehrer** [bauerca/drag-sort-listview#14]
I am using a list with a layout_margin, so the ListView is not the entire width of the screen.  In this case, the drag is fixed at x == 0, causing a visual problem.  I temporarily solved the problem by adding a property to DragSortListView to specify the X offset.  It would probably be better to have an attribute, or dynamically calculate that offset.

**Comment by bauerca** [comment]
Thanks for finding this!

**Comment by tracyboehrer** [comment]
Thank you for fixing it.  Best drag ListView I've tried so far.
