### ISSUE TITLE
Collapsed content (sometimes) visible

### ISSUE THREAD

**Issue by tracyboehrer** [bauerca/drag-sort-listview#15]
I am using a small collapsed height (1dp).  My row content is centered vertically.  Sometimes (often) when a row collapses, I can see pieces of the collapsed content.  The funny thing is, as I drag the row up/down, the visible content will occasionally go away, then come back.

I tried overriding onLayout in my view class and detecting when it's collapsed (which I can) and taking some action.  But I can't get it to behave consistently.

Can you suggest any work arounds for this?

**Comment by bauerca** [comment]
I have recently noticed this bug as well. I will try to track this down today. Thanks! I don't see an immediate workaround, as there is no callback for drag initiation; I will add such a callback with this fix.

**Comment by bauerca** [comment]
Do you have a typical drag scenario where this occurs? This would help with debugging.

**Comment by bauerca** [comment]
Okay found a bug. Let me know if this doesn't fix your case.

**Comment by tracyboehrer** [comment]
Excellent, thanks.  Seems to work perfect now.
