### ISSUE TITLE
DragSortListActivity|Fragment

### ISSUE THREAD

**Issue by saik0** [bauerca/drag-sort-listview#17]
My own attempt to copypasta ListFragment from support lib and replace with dslv was unsuccessful. Buggy behavior, seems to not be parsing attrs on inflate.  I'm not so familiar with dslv so I'm not sure what is causing the bug.  Do we want a Fragment and Activity in the project?

**Comment by bauerca** [comment]
So, if I understand correctly, you are using DSLV in a ListFragment from the android support library, and it isn't working? If so, I think I need to see some code to chase this one down. Thanks.

**Comment by bauerca** [comment]
Closing this. Pretty inactive. Feel free to reopen.
-Carl

**Comment by hzardaryan** [comment]
Hello,

I have tried to use DragSortListView with ListFragment it doesn't work. What i did?

1) I have this layout:

<RelativeLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent" >

```
<com.mobeta.android.dslv.DragSortListView
xmlns:dslv="http://schemas.android.com/library/res/com.mobeta.android.dslv"
android:id="@android:id/list"
android:layout_width="fill_parent"
android:layout_height="fill_parent"
dslv:drag_enabled="true"
dslv:collapsed_height="2dp"
dslv:drag_scroll_start="0.33"
dslv:max_drag_scroll_speed="0.5"
dslv:float_alpha="0.6"
dslv:slide_shuffle_speed="0.3"
dslv:track_drag_sort="false"
dslv:use_default_controller="true"
dslv:sort_enabled="true"
dslv:remove_enabled="true"
dslv:drag_start_mode="onLongPress"
dslv:remove_mode="flingLeft"
dslv:drag_handle_id="@id/drag_handle" />

<LinearLayout
    style="@style/LibraryList.Empty.Layout" 
    android:id="@android:id/empty">
</LinearLayout>
```

</RelativeLayout>

2) I have super simple adapter (for testing):
    public class SimpleAdapter extends ArrayAdapter<String> {

```
    public SimpleAdapter(List<String> list) {
        super(Player.this, R.layout.jazz_artist_list_item, R.id.artist_name_textview, list);
    }

    public View getView(int position, View convertView, ViewGroup parent) {
        LayoutInflater li = (LayoutInflater) getContext().getSystemService(
                Context.LAYOUT_INFLATER_SERVICE);
        View view = li.inflate(R.layout.jazz_artist_list_item, null);

        return view;
    }
}
```

3) I have layout for the list items (it is the same as in the example)

4) I have an activity that does the following onCreate():

protected void onCreate(Bundle savedInstanceState) {
super.onCreate(savedInstanceState);
        setContentView(R.layout.some_layout_that_contain_fragment);

DragSortListView list = (DragSortListView) findViewById(android.R.id.list);

```
    List<String> items = new ArrayList<String>();
    items.add("1");
    items.add("2");
    items.add("3");
    items.add("4");
    items.add("5");
    items.add("6");
    items.add("7");
    list.setAdapter(new SimpleAdapter(items));
```

}

So, i can see items in the List, but when i try to grab the handle and reorder them, the list is just scrolled.

PS
I have tried the demo and played with it and it works fine but it uses a ListActivity.

**Comment by bauerca** [comment]
I've looked through your code and cannot find the immediate problem. But, I think you have left out some things. Do you set a DropListener and RemoveListener on the DSLV? Where's your Fragment code?

Before sending more code, please have a look at [DSLVFragment.java](https://github.com/bauerca/drag-sort-listview/blob/master/demo/src/com/mobeta/android/demodslv/DSLVFragment.java) which is a ListFragment. It is used in the TestBedDSLV.java/"Playground" demo. The playground activity is a complicated one, but I think the answers you seek are within that example.

Hope this helps.

**Comment by hzardaryan** [comment]
I have checked the example you mentioned, it looks fine and dandy, i haven't noticed anything that my code misses. What i did, i started from scratch by creating super simple app with one FragmentActivity, what happens is list just gets scrolled when i try to grab the handle and move the item.

public class TestActivity extends FragmentActivity {

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_test);

    if (savedInstanceState == null) {
        getSupportFragmentManager().beginTransaction()
                .add(R.id.test_bed, new TestFragment(), "tag").commit();
    }

}

public class TestFragment extends ListFragment {
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.list_fragment, container, false);

        return view;
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

        List<String> items = new ArrayList<String>();
        items.add("1");
        items.add("2");
        items.add("3");
        items.add("4");
        items.add("5");
        items.add("6");
        items.add("7");

        final SimpleAdapter adapter = new SimpleAdapter(items);

        DragSortListView list = (DragSortListView) findViewById(android.R.id.list);
        list.setRemoveListener(new RemoveListener() {

            public void remove(int which) {
                adapter.remove(adapter.getItem(which));
            }
        });

        list.setDropListener(new DropListener() {

            public void drop(int from, int to) {
                String item = adapter.getItem(from);

                adapter.remove(item);
                adapter.insert(item, to);
            }
        });
        list.setEnabled(true);

        list.setAdapter(new SimpleAdapter(items));
    }

}

public class SimpleAdapter extends ArrayAdapter<String> {
    public SimpleAdapter(List<String> list) {
        super(TestActivity.this, R.layout.list_item_handle_right, R.id.text, list);
    }
}
```

}

Where (taken from DSLV original example), activity_test.xml is:

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/test_bed"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent" />

list_fragment.xml is:

<?xml version="1.0" encoding="utf-8"?>
    <com.mobeta.android.dslv.DragSortListView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:dslv="http://schemas.android.com/library/res/com.mobeta.android.dslv"
    android:id="@android:id/list"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    dslv:drag_enabled="true"
    dslv:collapsed_height="2dp"
    dslv:drag_scroll_start="0.33"
    dslv:max_drag_scroll_speed="0.5"
    dslv:float_alpha="0.6"
    dslv:slide_shuffle_speed="0.3"
    dslv:track_drag_sort="false"
    dslv:use_default_controller="true"
    dslv:sort_enabled="true"
    dslv:remove_enabled="true"
    dslv:drag_start_mode="onLongPress"
    dslv:remove_mode="flingLeft"
    dslv:drag_handle_id="@id/drag_handle" />

list_item_handle_right.xml is:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
  xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="fill_parent"
  android:layout_height="60dp"
  android:orientation="horizontal">
  <TextView
    android:id="@+id/text"
    android:layout_width="wrap_content"
    android:layout_height="60dp"
    android:layout_weight="1"
    android:textAppearance="?android:attr/textAppearanceMedium"
    android:gravity="center_vertical"
    android:paddingLeft="8dp" />
  <ImageView
    android:id="@id/drag_handle"
    android:background="@drawable/drag"
    android:layout_width="wrap_content"
    android:layout_height="60dp"
    android:layout_weight="0" />
</LinearLayout>

**Comment by hzardaryan** [comment]
ok, the issue is fixed now and list works super nicely. I have added the following:

list.setOnTouchListener(controller);

Thanks for support! The list is awesome :+1:

**Comment by bauerca** [comment]
Hm, glad to hear it! but you shouldn't need to do that if you have `dslv:use_default_controller="true"`. Wonder what happened...

**Comment by orac** [comment]
In my app, I had to use the package name of my app as the XML namespace, not DSLV's package name, because all the resources get added to my app by the library project system. That's probably what's going on here. I expect that if you replace `xmlns:dslv="http://schemas.android.com/library/res/com.mobeta.android.dslv"` with `xmlns:dslv="http://schemas.android.com/library/res-auto"` it will all work perfectly. (The build system automatically replaces `res-auto` with the namespace for the current project.)

Possibly the examples should be updated to use this style of naming instead of what they have now, to avoid further confusion. @bauerca Would you like me to put together a pull request with such a change?

**Comment by bauerca** [comment]
Ah, of course. Thanks Dan should've noticed that. I'll modify the demo proj.
