### ISSUE TITLE
zero collapsed_height

### ISSUE THREAD

**Issue by UgglyNoodle** [bauerca/drag-sort-listview#21]
Thanks so much for creating DragSortListView. I am currently using it my app [Regularly](https://play.google.com/store/apps/details?id=com.ugglynoodle.regularly) and it works great.

Just one question - is there a reason that collapsed_height cannot be 0dp? This behaviour would be much more aesthetically pleasing to me, since the lower items would not jiggle up and down when rearranging the upper items. However, when I try using 0dp, the list behaves unpredictably.

I haven't spent time yet to read your code and figure it out - thought maybe you would have a quick answer! Otherwise, I'll be happy to look into the issue myself.

**Comment by UgglyNoodle** [comment]
Actually, I just realised that the jiggling is due to the extra list divider that is created. I didn't notice this before because I am using transparent dividers. Setting android:dividerHeight="0dp" gives me exactly the behaviour I want. While I still don't know why mItemHeightCollapsed = 1 and not 0, I'm happy that it works as I wish.

Thanks again for a great, easy-to-use library!

**Comment by bauerca** [comment]
Thanks, you're welcome, and nice app! 

ListView doesn't like 0 heights in general (still haven't found the offending code in ListView.java), so unfortunately there's no easy fix. I'm testing a workaround at the moment.

Thanks for using and letting me know your app name.

Stay posted, I just implemented shuffle animations (list items slide around underneath the floating item); should show up on next commit.

Cheers!

**Comment by UgglyNoodle** [comment]
Excellent, shuffle animations would be great and I look forward to updating!

By the way, I wanted to thank you and let you know about my app earlier, but I couldn't find a way to contact you apart from posting an issue! There may be others who would like to let you know about their apps using DragSortListView but are unable to.

**Comment by bauerca** [comment]
Thanks. That's good advice. I'll get my email out there.
