### ISSUE TITLE
Improve drag listener

### ISSUE THREAD

**Issue by roee88** [bauerca/drag-sort-listview#22]
_Feature request_

The current listeners does not notify on drag start/stop.
This limits the ability to customize the views on drag operation. 

e.g. while dragging a special header item one may want to hide its sub items or modify its content before getDrawingCache is called for the floating view.

See  [com/ericharlow/DragNDrop/DragNDropListView.java](https://github.com/ericharlow/TICEWidgets/blob/master/DragNDropList/src/com/ericharlow/DragNDrop/DragNDropListView.java)  as a reference.

This is the only shortcoming I found compared to similar libraries.
Thank you for the lib.

**Comment by bauerca** [comment]
You are correct in that there is no "drag start" listener; I am aware of this and will soon provide one. However, you _can_ specify a DropListener to detect drag stop. Thanks.

**Comment by bauerca** [comment]
You can now customize the floating View to your heart's content with the new API. Check out the updated README for an overview, and the [API docs](http://bauerca.github.com/drag-sort-listview) for more details. Thanks.
