### ISSUE TITLE
unpredictable behaviour for slide_shuffle_speed < 0.5

### ISSUE THREAD

**Issue by UgglyNoodle** [bauerca/drag-sort-listview#26]
I love the shuffle animations! They look great and they will definitely be in the next version of my app.

I did notice that values of slide_shuffle_speed less than 0.5 caused strange behaviour. I think that the behaviour at slide_shuffle_speed = 0.5 is what you advertise as the slide_shuffle_speed = 0 behaviour. Having a quick look at the code, I think that you might be missing a factor of 0.5 when you convert from slide_shuffle_speed to mSlideRegionFrac.

**Comment by UgglyNoodle** [comment]
Actually, even for slide_shuffle_speed > 0.5, I'm noticing some weird behaviour if the list dividerHeight is large. Specifically, I see shuddering as I drag the item over the dividers.

One more thing: dividers appearing and disappearing at the bottom of the list is a little odd. (I understand that it makes sense in the middle of the list as gaps appear/disappear between list items.)

**Comment by bauerca** [comment]
Okay, definitely missed a 0.5. Thanks. I committed that fix just now and am currently working on the other issues. I appreciate the testing!

**Comment by bauerca** [comment]
Agreed on the divider issue. Lots to do! Thanks.

**Comment by bauerca** [comment]
things seem pretty smooth for me now. Great if you could confirm. Thanks!

**Comment by UgglyNoodle** [comment]
Tried it out right away with a few different slide_shuffle_speed/dividerHeight configurations and everything looks perfectly smooth! Thanks for all the hard work!

Now I just have to make the difficult decision about my slide_shuffle_speed value... I love how it looks at slide_shuffle_speed = 0, but a higher value probably is more intuitive to users!
