### ISSUE TITLE
Mavenize

### ISSUE THREAD

**Issue by schildbach** [bauerca/drag-sort-listview#27]
If a pom.xml would exist, and - optionally - the artifact would be available on Maven central, it would be a lot easier to integrate drag-sort-listview into own projects.

**Comment by imminent** [comment]
I wouldn't call it "a lot easier". I use Maven for my dependencies, but it's literally copy 2 files from DSLV (3 if you don't have an ids.xml and want to add the `drag` id). And change the package to you're project package (which my IDE did automatically for me anyways). It takes some work to get a project onto the central repository, from what I've seen. But if it gets done I won't complain.

**Comment by bauerca** [comment]
Haven't used maven. Will do some learning tonight, see if it's worth it at this point. Thanks.

**Comment by imminent** [comment]
The pom.xml should be pretty trivial as there aren't any outside
dependencies. The difficulty is getting project on the central repository.
You should just need to define the artifact id and version.

**Comment by schildbach** [comment]
Created this pull request:
https://github.com/bauerca/drag-sort-listview/pull/35
