### ISSUE TITLE
bindView() called on each drag event

### ISSUE THREAD

**Issue by saik0** [bauerca/drag-sort-listview#28]
Not sure if this is a bug, but dslv is calling through to my CursorAdapter bindView method on every drag event. 

Is that to be expected?

**Comment by bauerca** [comment]
It is for certain drag motions. For example, when drag-scrolling, DSLV might need to know the heights of some off-screen items. It has to call getView and then measure the returned View to get this information.

If slide shuffle animations are turned on, then the items are constantly changing height. This may trigger a getView call from within ListView while it lays things out.

Are you noticing performance hits?

**Comment by saik0** [comment]
> Are you noticing performance hits?

Yep. I'm using a typical ViewHolder pattern to get values from my cursor and fill the views. A single drag/drop can call getView over a hundred times. The animations are choppy on my Nexus 7's A9, I shudder to think what it would be line on older devices. Do you have any advice on how to optimize the adapter?

**Comment by bauerca** [comment]
okay, looking into this. Maybe I can bypass ListView layout to improve performance. To be clear, you are using a recent commit with slide animations? Thanks.

**Comment by saik0** [comment]
Using master HEAD

**Comment by bauerca** [comment]
Okay, in my tests, getView (and therefore bindView) is only called during a drag-scroll (and only during a fast one at that). You should not see any bindView calls while not drag-scrolling (that is, while drag-sorting near the middle of the screen).

Nevertheless, my latest commit includes some code that reduces calls to getView during drag scrolls.

If you continue to see problems, maybe we should take a closer look at your Adapter. Do you implement a DragListener?

**Comment by saik0** [comment]
I'm going to be out of town for a week and will be unable to look into it. My tests showed getView called on any drag, not only drag scroll.  For what it's worth the sample data did fill the view enough to be scrollable. I will pull and check again when I get back and post my adapter/results.

**Comment by saik0** [comment]
Also,  no DragListener, only a sorting CursorWrapper/DropListener

**Comment by saik0** [comment]
It's much smoother when using a solid float_background_color, I had it set with with an opaque color. This may have something to do with my list selector resource, which is also opaque. Closing issue.

**Comment by bauerca** [comment]
We still haven't figured out the problem!

There are two ways getView() is called during a drag-sort:
1. DSLV needs the height of an item (say at position `n`) and cannot obtain the item View through a call to `getChildAt(n)`.
2. As a result of a drag-scroll, ListView layout has to introduce a previously offscreen item into the visible list.

I guess a `notifyDataSetChanged()` would cause all the items to be "re-gotten," but that would also cancel the drag-sort.

Unnecessary remeasuring of shuffling items can cause performance hits, but let's tackle the getView() problem first. :)

**Comment by saik0** [comment]
OK, pulled to latest commit. getView is still being called on all drag events.

**Comment by bauerca** [comment]
Grrr! :)

First thing to figure out is whether DSLV or ListView is making the getView() call.

There is only one function in DragSortListView.java that calls getView(), and that's the private getChildHeight(int) method. Can you put Log.d() statements before each call to getView() within getChildHeight that somehow identifies them? Make sure _not_ to scroll while dragging.

**Comment by saik0** [comment]
getView only called from getChildHeight when drag scrolling.

**Comment by saik0** [comment]
On closer inspection I can confirm getView is not being called on each drag event anymore! It is being called 22 times on each drag start. Is that normal?

**Comment by saik0** [comment]
More interesting profile data, getView called between ~120 and ~160 times when my  DragSortCursorAdapter gets filled with sample data containing 11 items.

**Comment by bauerca** [comment]
Regarding the drag start, no, 22 getView calls sounds very abnormal. Regarding the 140 getView() calls.....whoa. :) You haven't by chance set your DSLV layout_height to wrap_content have you? Can you post the relevant xml layout files (dslv one, and list item one)? Thanks.

**Comment by saik0** [comment]
I'm having a difficult time replicating this outside my project. Whatever is going on here, it's not a dslv bug. In any case we've shown that getView is not called on each drag event any longer. I'll open a new issue if I'm able to replicate.

**Comment by bauerca** [comment]
Okay great.

**Comment by saik0** [comment]
Found it, one of the dslv widget's parents is in a horizontal linear layout using layout_weight for width. When I change it to a fixed width getView is called as "normal"

**Comment by bauerca** [comment]
ah ha! Congratulations :)

**Comment by saik0** [comment]
I'm going to take a closer look at DSLV widget tonight when I get home. Is "getView called alot with variable measurement" a product of ListView or does it have something to do with DSLV needing to get the measurement of the row views to be able to drag-sort.?

**Comment by bauerca** [comment]
ListView. You don't know the width of the ListView until you know the width of the widest item---i.e. until you've measured _all_ of them.

**Comment by saik0** [comment]
Maybe I'm missing something. A more simplified example would be a horizontally aligned LinearLayout with two children, a dslv and some other view. Both have `layout_height="match_parent"` `layout_width="0dp"` and `layout_weight=1`. The DSLV width should be parent_width/2, why would it need to measure _any_ of the list's children?

**Comment by saik0** [comment]
Woah, if you take that last example and change the dslv to `layout_width="1dp" It stops making excessive getView calls and I get nice weighted width. What's going on here?

**Comment by saik0** [comment]
Ha, but the item will have a width of 1dp when it's dragging. I think that gave me a hint ;)

**Comment by bauerca** [comment]
I'm beginning to think this is a LinearLayout thing. Under certain conditions, ListView will call getView() inside its onMeasure() method. If your LinearLayout is repeatedly measuring the contained ListView (and the conditions are right), getView() could be called many times. When ListView.onMeasure() calls getView(), it passes position=0 to it. You could print out the position given to the numerous calls to getView() to see if this is a part of the problem. Just a suggestion.

**Comment by bauerca** [comment]
Okay I just set up dslv as one of two children of a LinearLayout and everything works just fine. No extraneous calls to getView().

**Comment by saik0** [comment]
See saik0/drag-sort-listview@f8eb2fdbbdd527f7259a32ee3131964b4703635e for a demonstration. 

`git clone -b layout_weight https://github.com/saik0/drag-sort-listview.git`

**Comment by saik0** [comment]
Forgot to mention, if you replace DragSortListView and SimpleDragSortCursorAdapter with a ListView and SimpleCursorAdapter, you get the same number of calls on the same positions. Most assuredly _not_ a different dslv bug.

**Comment by imminent** [comment]
Joel have you seen the Google session about ListView?I think it's a couple
years old now, but it might help you with figuring out your issues. They
cover a bit of reasons you cause extra get view calls.

**Comment by saik0** [comment]
@imminent I think @bauerca is correct.

```
When ListView.onMeasure() calls getView(), it passes position=0 to it.
```

Not look at

```
11-20 02:09:28.798: D/DebugSimpleCursorAdapter(25349): getView called | position=0 count=1
11-20 02:09:28.898: D/DebugSimpleCursorAdapter(25349): getView called | position=0 count=2
11-20 02:09:28.908: D/DebugSimpleCursorAdapter(25349): getView called | position=1 count=3
11-20 02:09:28.918: D/DebugSimpleCursorAdapter(25349): getView called | position=2 count=4
11-20 02:09:28.928: D/DebugSimpleCursorAdapter(25349): getView called | position=3 count=5
11-20 02:09:28.938: D/DebugSimpleCursorAdapter(25349): getView called | position=4 count=6
11-20 02:09:29.028: D/DebugSimpleCursorAdapter(25349): getView called | position=0 count=7
```

The others call on drag start also have position=0.

**Comment by saik0** [comment]
For anybody interested, setting `android:baselineAligned="false"` on the parent LinearLayout removed the condition that measured the ListView.

**Comment by bauerca** [comment]
Interesting, thanks.
