### ISSUE TITLE
Limit drag operation only to part of ListView and don't move with headers

### ISSUE THREAD

**Issue by tprochazka** [bauerca/drag-sort-listview#39]
Sometimes in necessary to limit drag&drop operation only to part of  ListView or skip some row. For example if I use several section inside of ListView separated with different row type (header). I want to limit sorting only to one section and also is not possible move with header.

**Limit to one section:**

Best would be if DropListener will have more methods like startDrag(int position) which will be return or set limit bounce for drag operation. I mean minimal and maximal position.

**Fixed headers:**

I use

``` @Override
        public boolean isEnabled(int position) {
            return getItemViewType(position) == DATA;
        }

        @Override
        public boolean areAllItemsEnabled() {
            return false;
        }
```

for header rows. I think that DragSortListView should handle disabled items like fixed and don't allow to move with it.

**Comment by bauerca** [comment]
You are in luck! A commit that is just around the corner provides enough external control of the drag process that you can implement this feature easily yourself. I'll let you know how to do this after the commit is made. Should be soon.

**Comment by bauerca** [comment]
There is now an example of this in the demo project. See the activity [Sections.java](https://github.com/bauerca/drag-sort-listview/blob/master/demo/src/com/mobeta/android/demodslv/Sections.java) for all the details.

**Comment by tprochazka** [comment]
Thanks. Very interesting solution a little bit more complicated that I mean, but more flexible.
