### ISSUE TITLE
License Info Needed

### ISSUE THREAD

**Issue by janders-evernote** [bauerca/drag-sort-listview#4]
Hi Carl,

Thanks for all the good work on the drag list view.  I'm going to be adding draggable items in our app and I'd love to use your library, but need you to adopt a license for me to be able to use it.  Will you license the source using Apache 2.0 or something similar, or put a file in the base directory stating that the code is free for anyone to use for any purpose?

I'll be happy to submit any fixes I have for bugs  I find along the way.

Thanks!
Jess

**Comment by bauerca** [comment]
The source file now contains the license. Apache 2.0. Would love to hear which published apps of yours use DSLV.
