### ISSUE TITLE
dropping to start position => does not work correctly

### ISSUE THREAD

**Issue by MFlisar** [bauerca/drag-sort-listview#40]
I've following problem, if I start dragging and try dropping to the start position, it is just staying at the position I drop it, that means it's EXACTLY at the position I release the item instead of aligning itself in the list again... it looks lightly transparent and stays optically in dragging mode... sometimes the item even vanishes...

Moving to a different position than the start position on the other hand is always working

**Comment by bauerca** [comment]
What does your DropListener do when `from` is the same as `to`?

**Comment by bauerca** [comment]
Okay, I've reproduced the problem. It happens when the DropListener does not cause a dataset change on the ListAdapter. This will happen if your DropListener ignores the case when `from == to`. Fixing...

**Comment by MFlisar** [comment]
I can't check that right now but I can confirm that my drop listener is working that way
