### ISSUE TITLE
Intellij errors with xml schema: ".../layout/dslv_fragment_main.xml:2: error: No resource identifier found for attribute 'drag_enabled' in package 'com.mobeta.android.demodslv'"

### ISSUE THREAD

**Issue by lowellk** [bauerca/drag-sort-listview#41]
I'm getting errors building the demo from within Intellij. They look like:

   ...
    [Demo] /Users/lowellk/Dropbox/prog/drag-sort-listview/demo/res/layout/dslv_fragment_main.xml:2: error: No resource identifier found for attribute 'drag_enabled' in package 'com.mobeta.android.demodslv'
   ...

The demo builds fine from the command line.

This is happening for each of the xml attributes in the dslv namespace. 

I don't know much about how android deals with xml namespaces. Any idea why they might be getting rejected in Intellij?

**Comment by lowellk** [comment]
Solved. You must make sure that when importing into intellij that you mark the non-demo part of the code as a library project.

**Comment by bauerca** [comment]
Whop!
