### ISSUE TITLE
Basic usage playground shows artifacts after changing orientation

### ISSUE THREAD

**Issue by budziq** [bauerca/drag-sort-listview#42]
Hi,

There is a problem with redrawing of list items in the "Basic Usage" activity after orientation change.

Steps to reproduce:
1. Enter "Basic Usage Playground" activity
2. Change device orientation (at least once, but witch each consecutive repetition there are more artifacts)
3. Start list item reorder

What can be observed:
1. List items are drawn multiple times. One set is frozen in place where the list was seen before reorder.
2. Second set is moved while reorder. 

Screenshots after changing from portrait to landscape and back while reordering items.
http://i.imgur.com/zY2SJ.png
http://i.imgur.com/gksDk.png

**Comment by bauerca** [comment]
Whoa. You are right. Thanks. This is due to a misuse of Fragments. Will fix.

**Comment by bauerca** [comment]
Squarshed it. Thanks!
