### ISSUE TITLE
FloatView default size

### ISSUE THREAD

**Issue by tprochazka** [bauerca/drag-sort-listview#43]
I don't know why your examples works, but when I tried new version FloatView was not exact size as in ListView but minimal width. I examine code and found that `SimpleFloatViewManager` generate `ImageView` without dimension specification and in `DragSortList` class in the `measureFloatView` is forced to use

```
ViewGroup.LayoutParams(ViewGroup.LayoutParams.FILL_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT)
```

if float view doesn't have own. But what is here parent? `ImageView` created in  `SimpleFloatViewManager` has no parent, it is not in layout. I think. Or no?

So I put this

```
iv.setLayoutParams(new ViewGroup.LayoutParams(v.getWidth(),v.getHeight()));
```

to the end of `SimpleFloatViewManager.onCreateFloatView()` method to keep exact size as original list item has. I think that this should be default behavior, or not?

**Comment by bauerca** [comment]
The parent is the DSLV. Look in the `measureFloatView()` code again and notice the call to `getChildMeasureSpec(...)`. When the float View layout width is FILL_PARENT, this method creates a measure spec with a definite width given by the current width of the DSLV. So FILL_PARENT is ok.

**Comment by tprochazka** [comment]
Hmm. I tried to log measured width in measureFloatView and I got this:

```
10-26 11:01:12.010: INFO/app(20249): w:975
10-26 11:01:12.020: INFO/app(20249): w:975
10-26 11:01:12.020: INFO/app(20249): w:975
10-26 11:01:12.020: INFO/app(20249): w:292
10-26 11:01:12.020: INFO/app(20249): w:292
```

First 3 calls is right parent width last two are bad. Interesting

**Comment by tprochazka** [comment]
This code is called many time during drag operation:

``` java
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);

        if (mFloatView != null) {
            if (mFloatView.isLayoutRequested()) {
                measureFloatView();
            }
        }
        mWidthMeasureSpec = widthMeasureSpec;
    }
```

and it's source of small width evaluation. I don't know why DragSortListView itself reevaluate its dimension and why get different width that parent width.

But is is really neccesary to update mFLoatView measure during drag operation?

**Comment by bauerca** [comment]
`measureFloatView()` won't be called in `onMeasure` if you don't request a layout on it. Are you doing anything to the float View in an `onDragFloatView()` callback (or anywhere else for that matter)?

**Comment by tprochazka** [comment]
This is your code. You call measureFloatView() in the on Measure. I didn't make any modification. I also use original SimpleFloatViewManager

**Comment by bauerca** [comment]
This is interesting. I wonder why it does the 3 correct measures, then goes bad. The more DSLV-relevant code you can show me (from your tests/app) the better. I do not see this behavior at all in my tests. Thanks!

I want to update mFloatView (only when a layout is requested on it) so that the user can dynamically change the size during the drag if they want to add some effect (like an explode remove :)).

**Comment by tsengvn** [comment]
I got the same problem with the above, try his fix and work like a charm

**Comment by bauerca** [comment]
Implemented. Sorry this was ignored for so long.
