### ISSUE TITLE
Eclipse Errors on project import

### ISSUE THREAD

**Issue by chsriman** [bauerca/drag-sort-listview#49]
Hi,

I just tried download and import this project into Eclipse. I see a lot of errors in the project. All of them are related to overriding a superclass method. For example:

method drag(int, int) of type DragSortCursorAdapter must override a super class method
method drop(int, int) of type DragSortCursorAdapter must override a super class method

and so on... 

Is this an issue with the library or am I doing something wrong?

**Comment by YouForgotWhat** [comment]
Right click on your library project and the demo project, click on "Java Compiler" in the side menu pane, and change your Java compiler from "1.5" to "1.6" (NOT "1.7"). Now click on Projects > Clean > Clean all projects. That should fix it for you.

What's happening here is that Oracle introduced the @Override annotation in Java version 1.6, which DSLV uses. Eclipse automatically defaults to Java 1.5 and changing this manually fixes your issues. Hope this helped.

**Comment by chsriman** [comment]
@YouForgotWhat ... It absolutely did... Thanks a lot... How could I forget this... I guess I should not be working on a long weekend...

**Comment by bauerca** [comment]
Nice. Thanks @YouForgotWhat
