### ISSUE TITLE
Source code has a mix of spaces and tabs

### ISSUE THREAD

**Issue by yincrash** [bauerca/drag-sort-listview#5]
The source has a mix of tabs and spaces. If you use an editor that has a tab length other than 2, it makes the source much harder to read.

**Comment by bauerca** [comment]
Thanks. I've been meaning to fix this. Looks abysmal on the github src browser.

**Comment by yincrash** [comment]
Also, do you have a specific license for use of this library? I'd like to use it! (and I might also have a contribution to make).

**Comment by bauerca** [comment]
Apache 2.0 is in the src file. I think I'll move it to a LICENSE file soon though. Glad you find it useful. Please let me know your app name so I can start tallying DSLV's dissemination.

**Comment by bauerca** [comment]
Also, looking fwd to the pull request :)

**Comment by bauerca** [comment]
Finally got around to the tab/spacing issue. Thanks.
