### ISSUE TITLE
No resource found that matches the given name at ('id' with value '@id/drag')

### ISSUE THREAD

**Issue by YouForgotWhat** [bauerca/drag-sort-listview#50]
Hi baureca,

I saw that someone already had this issue before and I read through that thread but couldn't figure out how to fix my issue. I was using an older version of DSLV before without any problems (not sure what the exact version number was, but I imported it around October 15th). Today, I deleted that project from my Eclipse workspace and imported the latest version of DSLV from your repository and set it up according to the instructions on your main page.

 However, whenever I try to run my android project, I get an error saying "No resource found that matches the given name at ('id' with value '@id/drag')". My drag item is a simple imageview and it worked flawlessly with the previous version of DSLV. It's only this new version that's causing issues for me. How can I fix this error? Thanks!

**Comment by bauerca** [comment]
Try using @+id instead. Dslv no longer supplies the drag id. You choose whatever id you want and register it with the DragSortController.

**Comment by YouForgotWhat** [comment]
Changing "@id/drag" to "@+id/drag" get's rid of my original error but the imageview isn't registered as the drag-handle. I'm assuming that the "/res/values/ids.xml" file in the demo is what tells the DragSortController what I want to use as the drag-handle? Or is there something else I need to do to get it to work? Thanks again!

**Comment by YouForgotWhat** [comment]
Alrite, if anyone else has this problem in the future, this is how I got everything to work properly again:
1. Add 'dslv:use_default_controller="true" ' to your listview layout file.
2. Add 'dslv:drag_handle_id="@id/[your_drag_handle_id]" ' to your listview layout file. [your_drag_handle_id] is the id that you set for your drag handle (in your XML listview row file).

Thanks baureca for your clarification!

**Comment by imminent** [comment]
Are you sure you aren't mixing the old way DSLV worked with the new? Carl
said that it no longer provides the id which means using the id.xml isn't
necessary. Add the drag handle id in your layout with @+id and then you can
refer to that id with @id

**Comment by YouForgotWhat** [comment]
I didn't realize we didn't need "ids.xml" anymore. I'll make the modifications in my project then. Thanks for the info!

**Comment by bauerca** [comment]
@YouForgotWhat Glad you worked it out and thanks for the step-by-step. I think another way to do it is put `@+id/drag` as the id of your drag handle view, then use `drag_handle_id="@id/drag"`. The second _should_ reference the id created by the first. Cheers!

**Comment by bauerca** [comment]
Just realized I repeated @imminent . durk.

**Comment by YouForgotWhat** [comment]
Sounds good, I just updated my step-by-step to reflect your guys' instructions. It should be more clear now for those who need it.

**Comment by rudakovsky** [comment]
I had the same issue with dslv:drag_handle_id="@id/drag_handle" in the layout xml.
I put controller.setDragHandleId(R.id.drag_handle); to the code and it solved the problem.
