### ISSUE TITLE
Very odd bug appeared on Gingerbread device

### ISSUE THREAD

**Issue by Pirdad** [bauerca/drag-sort-listview#52]
First of all, let me say that this is an absolutely awesome library. So thanks for this.

I've seen this odd bug only on Gingerbread devices so far and here's the description:
If you set a color for the listview's divider (xml), the listview will be using the divider's color to draw over the entire listview when you drag an item. When you drop the item, everything goes back to normal.

I've tested this with two colors, I'm not entirely sure if this occurs on all colors but here are the two colors I've tested with: #ffffff and #2a2c31

Here's the code for the xml layout:

<?xml version="1.0" encoding="utf-8"?>
<com.mobeta.android.dslv.DragSortListView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:dslv="http://schemas.android.com/apk/res/com.example.testdragsortlistgingerbread"
    android:id="@+id/layout_listview"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_margin="3dp"
    android:dividerHeight="1dp"
    android:divider="#2a2c31"
    android:padding="3dp"
    dslv:collapsed_height="2dp"
    dslv:drag_enabled="true"
    dslv:drag_scroll_start="0.33"
    dslv:float_alpha="0.6"
    dslv:max_drag_scroll_speed="0.5"
    dslv:slide_shuffle_speed="0.3"
    dslv:track_drag_sort="false"
    dslv:use_default_controller="false" />

Give this a try and let me know thanks.

**Comment by bauerca** [comment]
Just to clarify, if you leave out `android:divider="#2a2c31"`, does the problem go away?

**Comment by Pirdad** [comment]
Yes, that's correct.

**Comment by bauerca** [comment]
Well this is annoying. That line creates a ColorDrawable divider rather than the default which is a NinePatchDrawable divider. On gingerbread, the ColorDrawable.draw(Canvas) method ignores the bounds set in ColorDrawable.setBounds(). That's why it fills the screen! I will have to hack-fix this...yuck.

**Comment by Pirdad** [comment]
Wow, that's nasty. 
Ohh well, at least we know now.
Btw, Thanks for quick responses.
