### ISSUE TITLE
NullPointerException  RelativeLayout onMeasure

### ISSUE THREAD

**Issue by alexbeville** [bauerca/drag-sort-listview#57]
When I try to use your library, I was confronted to a NullPointerException on DragSortListView.measureItem.

After some inspection, I found that you check the LayoutParams, and if null, create new one. But this new LayoutParams is never set to the view. So here is my solution : 

Line 1937 Before :
if (lp == null) {
            lp = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.FILL_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
         }

Line 1937 After : 

if (lp == null) {
            lp = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.FILL_PARENT, ViewGroup.LayoutParams.WRAP_CONTENT);
            item.setLayoutParams(lp);
        }

**Comment by bauerca** [comment]
Is your RelativeLayout that is throwing the exception the floating View? I'd like to know b/c the floating View is not part of the android View hierarchy; logic in ViewGroup takes care of setting LayoutParams if there are none on a child. Therefore, I would only do `item.setLayoutParams(lp)` if the `measureItem()` call was on the floating View. Thanks.
