### ISSUE TITLE
Renaming the library project

### ISSUE THREAD

**Issue by aliHafizji** [bauerca/drag-sort-listview#58]
This might not be a very big issue, but I've got a number of project added as third party project to my app. The problem is that mostly all third party libraries name their libraries as "library". Would it be a good idea to name the library "dslvLibrary" that way it would not conflict with anything

**Comment by bauerca** [comment]
Not sure I see the issue. When you checkout this project, you already have the "drag-sort-listview/" qualifier directory to differentiate from other libs. Sounds like some build script finagling is needed.
