### ISSUE TITLE
List items not resized when its inner view changes

### ISSUE THREAD

**Issue by ricardojuanpalmaduran** [bauerca/drag-sort-listview#59]
The DragSortListView does not resize its elements properly when one tries to change the elements without going through the adapter.

So for instance, suppose that you have a regular ListView that contains regular TextViews. Each TextView has a height, but if you change the text in the TextView directly (not going through the adapter's notifyDataSetChanged()), the items are resized properly so the new text fits perfectly inside the list cell. This may sound a weird scenario, because one does not usually modify the views of the adapter's items directly, but via notifyDataSetChanged(). However, there are scenarios in which you can or even should access the item's view directly. My particular problem has to do with having a ListView that is populated with EditText views. When the user types some text in one of the EditTexts, it increases its height, and all the text that is typed fits perfectly within the cell that contains the EditText.

However, if I replace the ListView with a DragSortListView, then the above description is no longer true. When I use the DragSortListView, if I increase the size of the view of one of the list's items, even though the view increases its size (height), the list's cell does not, so as a result the view is cropped and is not displayed completely (the view is cropped). In the case of the list that is populated with EditText views, when the user starts typing some text in an EditText, the EditText increases its size, but the cell does not, and thus the list item does not display the whole content of the EditText.

However, if after doing this I refresh the DragSortListView via its adapter, the cells that were not being properly resized are now resized properly.

**Comment by bauerca** [comment]
Definitely a problem. Thanks for reporting this. I will look into it soon.

**Comment by oriolj** [comment]
I think that is not so strange scenario, I'm having the same problem:
I fill the list with imageviews with diferent heights, the image is downloaded and loaded to the imageview through an asynctask, before the image is loaded I put a "placeholder" image, i think that this is no that strange. 

Good work anyway love this lib.

**Comment by bauerca** [comment]
This should do it. Would love confirmation from you guys. Thanks!

**Comment by ricardojuanpalmaduran** [comment]
It works fine now. Thanks so much for your effort.

**Comment by oriolj** [comment]
+1 working
