### ISSUE TITLE
Too much free space

### ISSUE THREAD

**Issue by Learning-from-masters** [bauerca/drag-sort-listview#60]
Don't you think there's too much space down the close and wrap images if the text is a bit large?
I have tried to implement flowtextview in your project for correct it but I'm getting an error. Could you add this or something similar?

Here I give you my error:
 http://stackoverflow.com/questions/14091509/error-inflating-row-layout-in-a-listview

**Comment by bauerca** [comment]
Please pardon any misunderstandings, but your questions (including the stackoverflow posting) seem unrelated to DragSortListView operation. It sounds more like you are having issues implementing a custom View. The stackoverflow responses seem to be pointing in the right direction so far.
