### ISSUE TITLE
Eclipse, add xml wih DragSortListView causes errors

### ISSUE THREAD

**Issue by boris-dev** [bauerca/drag-sort-listview#65]
1) Add drag-sort-listview-0.3.0 project into workspace
2) Add drag-sort-listview-0.3.0 library into my project (properties->android->add library)
3) create view.xml with DragSortListView
4) Many errors like: 
...
Multiple annotations found at this line:
    - error: No resource identifier found for attribute 'drag_handle_id' in package 'com.mobeta.android.demodslv'
    - error: No resource identifier found for attribute 'drag_enabled' in package 'com.mobeta.android.demodslv'
    - error: No resource identifier found for attribute 'slide_shuffle_speed' in package 
     'com.mobeta.android.demodslv'
    - error: No resource identifier found for attribute 'use_default_controller' in package 
     'com.mobeta.android.demodslv'
    - error: No resource identifier found for attribute 'track_drag_sort' in package 'com.mobeta.android.demodslv'
...

What did I miss?

**Comment by bauerca** [comment]
I think you need to change 'com.mobeta.android.demodslv' to your project's package name.

**Comment by boris-dev** [comment]
Thank you! It works.

**Comment by actolap** [comment]
You can do it with auto discovery:
xmlns:dslv="http://schemas.android.com/apk/res-auto"
