### ISSUE TITLE
Disable sorting for certain items

### ISSUE THREAD

**Issue by julyate** [bauerca/drag-sort-listview#66]
This is a question, not an issue. 

I'm trying to implement a sortable listview, where only some of the items are sortable. For instance, the top three items in the list should not be draggable, and it should not be possible for other items to be dragged over them. 

Is there currently a defined way of doing this?

**Comment by julyate** [comment]
It appears that I was overlooking the obvious, in order to make the top rows unsortable, I added them as header views.

**Comment by bauerca** [comment]
Okay great. However, "locked-in" items _not_ at the extremities of the list are currently _unsupported_. Thanks.

**Comment by RomanIakovlev** [comment]
@bauerca I know it's an old issue and the project is not actively maintained. But maybe you or someone can still answer how to "lock-in" items at extremities? Is this possible only through headers or footers? I need to lock those items dynamically, but only at the beginning of the list. What's the best way to do this?

**Comment by julyate** [comment]
While I'm sure there are better methods of doing it, I stuck to the quickest/dirties way of doing it: I split up my data array in two separate arrays; one for the sortable and one for the unsortable data. Added the unsortable data to the headers, then set the sortable data on the adapter. Not the prettiest code I've ever written.
