### ISSUE TITLE
 ExpandableListView Support

### ISSUE THREAD

**Issue by serj-lotutovici** [bauerca/drag-sort-listview#67]
This is not an issue, it's more like a question.

Does the library support ExpandableListView? If not, will there be support in the future or perhaps someone knows how to implement such a feature like Drag-and-Drop for an ExpandableListView?

**Comment by bauerca** [comment]
Currently it does not support ELV. I have plans to, so stay posted. Thanks.

**Comment by tiger1990** [comment]
I was stuck in the issue , Someone hs suggested this library in github:
https://github.com/sreekumarsh/android/issues/5
This has serious issue, It don`t works on many device, example : Samsung S5, Iris X-9 etc.
If you have time you can just fork out his repo and make some changes that solves issue.
