### ISSUE TITLE
different views for dragging and removing items

### ISSUE THREAD

**Issue by ivanursul** [bauerca/drag-sort-listview#74]
Hello,here is my question:
Can i do a little trick by setting one view for deleting items and one view for dragging(sorting) items.for example,right button will be for dragging items
and green arean will be for deleting items.
Is this possible?)

**Comment by bauerca** [comment]
Sure. Check out the `click_remove_id` xml attr.

Edit:
And the `drag_handle_id` xml attr, of course.

**Comment by ivanursul** [comment]
i mean, i need two views,and when i touch one view,i need to drag item,and when i click to another view,i need to swipe to the left item(delete).
Is this possible?)

**Comment by bauerca** [comment]
The most recent release (0.6.0) has the feature you are looking for (I think). Set:

```
dslv:remove_enabled="true"
dslv:remove_mode="fling_remove"
dslv:fling_handle_id="@id/green"
```

Sorry if I continue to misunderstand.

**Comment by ivanursul** [comment]
Thank you.,that is the right what i was looking for )
