### ISSUE TITLE
Failed to retrieve view Tag object in onListItemClick

### ISSUE THREAD

**Issue by theboubougne** [bauerca/drag-sort-listview#75]
Hi,

I use your library in a ListFragment.
Prior to that I was using onListItemClick() retrieving the view Tag object. But now, I only retrieve a null object when calling view.getTag().
How come ?

**Comment by bauerca** [comment]
Try

```
((ViewGroup) view).getChildAt(0).getTag()
```

DSLV wraps the list items you produce in your adapter.

**Comment by theboubougne** [comment]
Thx a lot !
