### ISSUE TITLE
No more slideLeft ?

### ISSUE THREAD

**Issue by Tolriq** [bauerca/drag-sort-listview#78]
Hi,

With the last update it seems there's no more way to slide the draghandler for item removal.
Settings the fling_handle_id to the drag_handle does not work.

Is there any workaround to get back to the old behaviour ?

**Comment by Tolriq** [comment]
No one got an idea on this ? 

I was glad my PR was added to support that long time ago, but the last version render this lib unusable in viewpager if we want only one drag handler to sort and dismiss :(

**Comment by bauerca** [comment]
Are you using `dslv:drag_start_mode="onDown"`?

**Comment by Tolriq** [comment]
Yes since it's the default value.

**Comment by Tolriq** [comment]
After some more test it seems that using the same id for drag and fling and changing drag_start_mode to onMove may do the trick.

Thanks for the pointer will update if there s problem with some android version or roms.
