### ISSUE TITLE
Add Sections In between the ListItems

### ISSUE THREAD

**Issue by kendrelaxman** [bauerca/drag-sort-listview#8]
Hello,
I have used DSLV as a baseline and by using this I have created a Listview with sections in between the List Items something Like This will give you idea.

A ------> Saparator which should not be draggable
Afaganistan -----> List Item should be draggable
America-----> List Item should be draggable
B------> Saparator which should not be draggable
Bangladesh-----> List Item should be draggable
Bhutan-----> List Item should be draggable

for this I have used following code snippet but the Listview is getting crashed while dragging please check my code 

---

public class Customsection extends ListActivity {

```
private MyCustomAdapter mAdapter;

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.dslv_main);
    DragSortListView lv = (DragSortListView) getListView(); 

    lv.setDropListener(onDrop);
    lv.setRemoveListener(onRemove);
    mAdapter = new MyCustomAdapter();

    for (int i = 1; i < 50; i++) {
        mAdapter.addItem("item " + i);
        if (i % 4 == 0) {
            mAdapter.addSeparatorItem("separator " + i);
        }
    }
    setListAdapter(mAdapter);
}
private DragSortListView.DropListener onDrop =
          new DragSortListView.DropListener() {
            @Override
            public void drop(int from, int to) {
              String item = mAdapter.getItem(from);

              mAdapter.remove(item);
              mAdapter.insert(item, to);
            }
          };

        private DragSortListView.RemoveListener onRemove = 
          new DragSortListView.RemoveListener() {
            @Override
            public void remove(int which) {

                 mAdapter.remove(mAdapter.getItem(which));
            }
          };

private class MyCustomAdapter extends ArrayAdapter {

    private static final int TYPE_ITEM = 0;
    private static final int TYPE_SEPARATOR = 1;
    private static final int TYPE_MAX_COUNT = TYPE_SEPARATOR + 1;

    private ArrayList mData = new ArrayList();
    private LayoutInflater mInflater;

    private TreeSet mSeparatorsSet = new TreeSet();

    public MyCustomAdapter() {
         super(Customsection.this, R.layout.item1,
              R.id.textSeparator);
        mInflater = (LayoutInflater)getSystemService(Context.LAYOUT_INFLATER_SERVICE);
    }

    public void addItem(final String item) {
        mData.add(item);
        notifyDataSetChanged();
    }

    public void addSeparatorItem(final String item) {
        mData.add(item);
        // save separator position
        mSeparatorsSet.add(mData.size() - 1);
        notifyDataSetChanged();
    }

    @Override
    public int getItemViewType(int position) {
        return mSeparatorsSet.contains(position) ? TYPE_SEPARATOR : TYPE_ITEM;
    }

    @Override
    public int getViewTypeCount() {
        return TYPE_MAX_COUNT;
    }

    @Override
    public int getCount() {
        return mData.size();
    }

    @Override
    public String getItem(int position) {
        return (String) mData.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        ViewHolder holder = null;
        int type = getItemViewType(position);
        System.out.println("getView " + position + " " + convertView + " type = " + type);
        if (convertView == null) {
            holder = new ViewHolder();
            switch (type) {
                case TYPE_ITEM:
                    convertView = mInflater.inflate(R.layout.item1, null);
                    holder.textView = (TextView)convertView.findViewById(R.id.text);
                    break;
                case TYPE_SEPARATOR:
                    convertView = mInflater.inflate(R.layout.item2, null);
                    holder.textView = (TextView)convertView.findViewById(R.id.textSeparator);
                    break;
            }
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder)convertView.getTag();
        }
        holder.textView.setText(mData.get(position).toString());
        return convertView;
    }

}

public static class ViewHolder {
    public TextView textView;
}
```

}

**Comment by kendrelaxman** [comment]
stack trace for above code is

08-09 10:25:25.477: E/AndroidRuntime(306): FATAL EXCEPTION: main
08-09 10:25:25.477: E/AndroidRuntime(306): java.lang.IndexOutOfBoundsException: Invalid index 1, size is 0
08-09 10:25:25.477: E/AndroidRuntime(306):  at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:257)
08-09 10:25:25.477: E/AndroidRuntime(306):  at java.util.ArrayList.add(ArrayList.java:152)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.widget.ArrayAdapter.insert(ArrayAdapter.java:196)
08-09 10:25:25.477: E/AndroidRuntime(306):  at com.mobeta.android.demodslv.Customsection$1.drop(Customsection.java:47)
08-09 10:25:25.477: E/AndroidRuntime(306):  at com.mobeta.android.dslv.DragSortListView.dropFloatView(DragSortListView.java:795)
08-09 10:25:25.477: E/AndroidRuntime(306):  at com.mobeta.android.dslv.DragSortListView.onTouchEvent(DragSortListView.java:987)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.view.View.dispatchTouchEvent(View.java:3766)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:897)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:936)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:936)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:936)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:936)
08-09 10:25:25.477: E/AndroidRuntime(306):  at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1671)
08-09 10:25:25.477: E/AndroidRuntime(306):  at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1107)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.app.Activity.dispatchTouchEvent(Activity.java:2086)
08-09 10:25:25.477: E/AndroidRuntime(306):  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1655)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.view.ViewRoot.handleMessage(ViewRoot.java:1785)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.os.Handler.dispatchMessage(Handler.java:99)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.os.Looper.loop(Looper.java:123)
08-09 10:25:25.477: E/AndroidRuntime(306):  at android.app.ActivityThread.main(ActivityThread.java:4627)
08-09 10:25:25.477: E/AndroidRuntime(306):  at java.lang.reflect.Method.invokeNative(Native Method)
08-09 10:25:25.477: E/AndroidRuntime(306):  at java.lang.reflect.Method.invoke(Method.java:521)
08-09 10:25:25.477: E/AndroidRuntime(306):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
08-09 10:25:25.477: E/AndroidRuntime(306):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
08-09 10:25:25.477: E/AndroidRuntime(306):  at dalvik.system.NativeStart.main(Native Method)

**Comment by bauerca** [comment]
You're not actually adding your items to the ArrayAdapter super class. You should replace your `addItem(...)` method with

```
@Override
public void add(String item) {
    super.add(item);
    ...
}
```
