### ISSUE TITLE
Rowview background does not represent state

### ISSUE THREAD

**Issue by gabrielittner** [bauerca/drag-sort-listview#82]
I have a state-list drawable as background for my rowviews. When I call setCheckedItem the background of the rowview should change to the one defined in the state-list. 
This doesn't happen when I use the DragSortListView. When I just change the xml back to ListView it works fine, so I don't think it's an issue on my side.

**Comment by gabrielittner** [comment]
I have to specify the problem a little further. The checked state works fine, but on API11+ the default ListView calls setActivated() on the rowview if it isn't checkable. This is the thing that doesn't happen when using the DragSortListView.

**Comment by bauerca** [comment]
Okay, so the problem is that DragSortItemView (which wraps all DSLV list items) is always an instance of Checkable, which means that setActivated() will never get called by ListView. Argh.

Working on the fix; stay tuned...

**Comment by bauerca** [comment]
Please test! Thanks.
-Carl

**Comment by gabrielittner** [comment]
It works. Thanks a lot :)

**Comment by homj** [comment]
It's not working for me... I'm on API 16
