### ISSUE TITLE
FloatView problem on Holo Theming

### ISSUE THREAD

**Issue by devisnik** [bauerca/drag-sort-listview#84]
I've set the Launcher App theme to Holo.Light, using minSDKVersion=11. When dragging, the float view is messed up. This is on my Galaxy Nexus, running Android 4.2.2.

![dslv_on_holo_light-2013-03-14-180757](https://f.cloud.github.com/assets/1219911/259934/9281886e-8cca-11e2-9d0c-4332ac292181.png)

**Comment by bauerca** [comment]
The problem is the background color of the floating View, which is not aware of any theme and defaults to black. See `float_background_color` here: https://github.com/bauerca/drag-sort-listview#xml-attributes. Just set that xml attr to whatever you need for now. Thanks.

**Comment by devisnik** [comment]
Ah, great, works like a charm now. Thanks. I wonder why the background color is fine by default when using Theme.Light though.

**Comment by jmmcreynolds** [comment]
Perfect! I ran into this the other day and thought it was something I was doing, but hadn't really looked into it. Now I don't have to try to figure it out. :)
