### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by rokasjasonas** [bauerca/drag-sort-listview#90]
Dont know how it happened. User reported on my app. I use newest version with features: swype to remove, long press to drag. 

0java.lang.IndexOutOfBoundsException
1at java.util.Arrays$ArrayList.get(Arrays.java:75)
2at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:298)
3at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:351)
4at android.widget.ArrayAdapter.getView(ArrayAdapter.java:323)
5at android.widget.Spinner.makeAndAddView(Spinner.java:193)
6at android.widget.Spinner.layout(Spinner.java:152)
7at android.widget.Spinner.onLayout(Spinner.java:116)
8at android.view.View.layout(View.java:7175)
9at android.widget.RelativeLayout.onLayout(RelativeLayout.java:912)
10at android.view.View.layout(View.java:7175)
11at android.widget.RelativeLayout.onLayout(RelativeLayout.java:912)
12at android.view.View.layout(View.java:7175)
13at android.widget.ListView.setupChild(ListView.java:1899)
14at android.widget.ListView.makeAndAddView(ListView.java:1814)
15at android.widget.ListView.fillDown(ListView.java:736)
16at android.widget.ListView.fillSpecific(ListView.java:1368)
17at android.widget.ListView.layoutChildren(ListView.java:1642)
18at com.mobeta.android.dslv.DragSortListView.layoutChildren(DragSortListView.java:2099)
19at android.widget.AbsListView.onLayout(AbsListView.java:1366)
20at android.view.View.layout(View.java:7175)
21at android.widget.RelativeLayout.onLayout(RelativeLayout.java:912)
22at android.view.View.layout(View.java:7175)
23at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
24at android.view.View.layout(View.java:7175)
25at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1254)
26at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1130)
27at android.widget.LinearLayout.onLayout(LinearLayout.java:1047)
28at android.view.View.layout(View.java:7175)
29at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
30at android.view.View.layout(View.java:7175)
31at android.widget.FrameLayout.onLayout(FrameLayout.java:338)
32at android.view.View.layout(View.java:7175)
33at android.view.ViewRoot.performTraversals(ViewRoot.java:1146)
34at android.view.ViewRoot.handleMessage(ViewRoot.java:1866)
35at android.os.Handler.dispatchMessage(Handler.java:99)
36at android.os.Looper.loop(Looper.java:130)
37at android.app.ActivityThread.main(ActivityThread.java:3687)
38at java.lang.reflect.Method.invokeNative(Native Method)
39at java.lang.reflect.Method.invoke(Method.java:507)
40at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
41at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
42at dalvik.system.NativeStart.main(Native Method)

**Comment by orac** [comment]
Does your list item layout contain a Spinner, by any chance? The crash
appears to be there. Could you be changing the ArrayList you passed to
the spinner's adapter behind its back? Reading the stack trace from
bottom to top, you can see the DSLV is doing a layout (line 18), which
is going down to its children (lines 13-17). The child RelativeLayout is
trying to layout a child Spinner (line 7), and it's when that Spinner
calls through to its Adapter (an ArrayAdapter, line 4) that the crash
occurs: when the ArrayAdapter tries to get an item from the array. I
wouldn't expect ArrayAdapter to overrun the bounds of the array it's
passed unless something odd had happened, and the array being resized is
the most obvious candidate.
Please double-check your code.
