### ISSUE TITLE
another crash

### ISSUE THREAD

**Issue by rokasjasonas** [bauerca/drag-sort-listview#91]
0java.lang.NullPointerException
1at com.mobeta.android.dslv.DragSortListView.updateFloatView(DragSortListView.java:2343)
2at com.mobeta.android.dslv.DragSortListView.doDragFloatView(DragSortListView.java:2273)
3at com.mobeta.android.dslv.DragSortListView.doDragFloatView(DragSortListView.java:2267)
4at com.mobeta.android.dslv.DragSortListView.continueDrag(DragSortListView.java:1769)
5at com.mobeta.android.dslv.DragSortListView.onDragTouchEvent(DragSortListView.java:2130)
6at com.mobeta.android.dslv.DragSortListView.onTouchEvent(DragSortListView.java:1611)
7at android.view.View.dispatchTouchEvent(View.java:5681)
8at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1951)
9at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1712)
10at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
11at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
12at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
13at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
14at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
15at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
16at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:1957)
17at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1726)
18at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2063)
19at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1399)
20at android.app.Activity.dispatchTouchEvent(Activity.java:2364)
21at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2011)
22at android.view.View.dispatchPointerEvent(View.java:5861)
23at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3094)
24at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2614)
25at android.view.ViewRootImpl.processInputEvents(ViewRootImpl.java:978)
26at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2623)
27at android.os.Handler.dispatchMessage(Handler.java:99)
28at android.os.Looper.loop(Looper.java:137)
29at android.app.ActivityThread.main(ActivityThread.java:4507)
30at java.lang.reflect.Method.invokeNative(Native Method)
31at java.lang.reflect.Method.invoke(Method.java:511)
32at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
33at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
34at dalvik.system.NativeStart.main(Native Method)

**Comment by widmoser** [comment]
What was the reason for this issue? How did you fix it?
