### ISSUE TITLE
null pointer

### ISSUE THREAD

**Issue by rokasjasonas** [bauerca/drag-sort-listview#93]
0   java.lang.NullPointerException
1   at com.mobeta.android.dslv.DragSortListView.updateFloatView(DragSortListView.java:2343)
2   at com.mobeta.android.dslv.DragSortListView.doDragFloatView(DragSortListView.java:2273)
3   at com.mobeta.android.dslv.DragSortListView.doDragFloatView(DragSortListView.java:2267)
4   at com.mobeta.android.dslv.DragSortListView.access$8(DragSortListView.java:2259)
5   at com.mobeta.android.dslv.DragSortListView$DropAnimator.onUpdate(DragSortListView.java:1267)

**Comment by widmoser** [comment]
I've got the same issue. What was the reason you had it? How did you fix it?
