### ISSUE TITLE
Swipe to delete mode

### ISSUE THREAD

**Issue by trietbui85** [bauerca/drag-sort-listview#94]
I see in DSLV, we can swipe to right or to left to remove item.
But for some reason (I'm using DSLV in SlidingMenu), I don't want to swipe to left.

Can you add such flag?

**Comment by bauerca** [comment]
Sorry, this is best implemented on your own. Thanks.

**Comment by NtcWai** [comment]
I have just read in there:
https://github.com/bauerca/drag-sort-listview/issues/98
try it :)
