### ISSUE TITLE
Using fling remove with viewpager

### ISSUE THREAD

**Issue by pavelkorolevxyz** [bauerca/drag-sort-listview#98]
I have viewpager with 3 screens, left screen has DragSortListView, I want to remove items from this list by fling from left to right and go to second screen on right to left fling. Is there any way to do this with latest version of library? Thanks!

**Comment by bauerca** [comment]
Sure thing. On [this line](https://github.com/bauerca/drag-sort-listview/blob/master/library/src/com/mobeta/android/dslv/DragSortController.java#L393), change `Math.abs(x2 - x1)` to `(x2 - x1)`.
